version: '3'

services:
  app: 
    image: quan/hotel:latest
    build:
      context: .
    container_name: app
    restart: always
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/hotel-management
      - SPRING_DATASOURCE_USERNAME=quan
      - SPRING_DATASOURCE_PASSWORD=1996
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    depends_on:
      - db
    networks:
      - shared-net

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    environment: 
      POSTGRES_USER: quan
      POSTGRES_PASSWORD: 1996
      POSTGRES_DB: hotel-management
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - shared-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: always
    networks:
      - shared-net
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    restart: always
    networks:
      - shared-net

volumes:
  db_data: 

networks:
  shared-net:
    driver: bridge